# Generated by Django 5.0.4 on 2024-04-24 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeluser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='modeluser',
            name='reset_password',
        ),
        migrations.DeleteModel(
            name='ModelAddress',
        ),
    ]
